### ISSUE TITLE
Poder instalarlo globalmente con -g

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#10]
El objetivo final es que funcione como npm-check-updates, en el sentido de que al instalarlo con -g queda instalado de manera que pueda invocarse sin buscarlo en la carpeta y sin ponerle delante node o npm.

**Comment by diegoefe** [comment]
ok, lo investigo cuando termino con #13

**Comment by diegoefe** [comment]
Ya se puede probar si funciona el -g (se corre con multilang ....)

**Comment by emilioplatzer** [comment]
Funciona desde la carpeta donde está el multilang, por ejemplo:

``` sh
c:\desarrollo\multilang> npm install -g
```

pero no funciona si se lo llama desde cualquier otra:

``` sh
c:\cualquier\otra> npm install -g multilang
```

pone en la carpeta roaming en node_modules todo lo que baja pero no agrega los dos scripts que lo corren

**Comment by emilioplatzer** [comment]
Andaba todo bien. Solo faltaba publicar la versión nueva. Ahora lo puse en 1.0.0, estable.
