### ISSUE TITLE
Bug de efectos colaterales de getWarnings

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#12]
getWarnings tiene efectos colaterales. Para reproducir este bug hay que bajarse los módulos
- tabulator y 
- multilang

e instalar multilang y correr esto desde multilang. 

``` js
c:\hecho\npm\multilang> node bin\multilang-run.js c:\hecho\npm\tabulator\README.md
```

Funciona bien

Luego hay que modificar multilang.js y descomentar las siguientes 3 líneas (de la 302 a la 304):

``` js
        // comentar estas 3:
        if(!parameters.silent){
            (parameters.chanerr || process.stderr).write(multilang.getWarnings(readContent));
        }
```

Luego volver a ejecutar

``` sh
c:\hecho\npm\multilang>node bin\multilang-run.js c:\hecho\npm\tabulator\README.md
Using directory:  c:\hecho\npm\tabulator
Processing 'c:\hecho\npm\tabulator\README.md'...
Generating all languages...
ERROR
Error: ENOENT, no such file or directory 'c:\hecho\npm\multilang\langs\lang-[object Object].yaml'
c:\hecho\npm\multilang>
```

al correr lo mismo ahora da un error. Evidentemente el problema es la invocación del getWarnings.

**Comment by diegoefe** [comment]
Corrected on commit 38bf36fa01228b36f1d04f657a51b290a70e221f
