### ISSUE TITLE
Verificar la lógica de los warnings

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#13]
El algoritmo que revise los warnings de los lenguajes debe considerar la directiva lang:xx actual y la directiva lang:xx anterior. Se debe parsear en orden cada directiva lang:xx
1. la primera vez:
   1. que se encuentra un lang:xx, xx debe ser el lenguaje principal o el siguiente (si son dos puede ser cualquiera de ellos). 
   2. la primera vez debe comenzar con "<".
2. las veces subsiguientes:
   1. el lenguaje principal y el "*" cierran con ">" (significa seguir visible) los demás con "]" (significa seguir invisible)
   2. el signo de apertura de la directiva depende del cierre de la directiva anterior (si cerró con "]" el actual abre con "[") 
   3. el lenguaje actual debe ser el siguiente del anterior (en la lista de definición de lenguajes) y si es "*" el anterior debe ser el último lenguaje y si es main el anterior es el último lenguaje o "*". 
3. al final de todo (cuando no hay más lenguajes) hay que revisar el último que se había visto y:
   1. el lenguaje debe ser el último o *

**Comment by diegoefe** [comment]
Ayudame a pensar si esto es correcto:
Para saber que terminó una sección (y que empieza la siguiente), detecto el primer lenguage.
Correcto?

**Comment by emilioplatzer** [comment]
No te importa cuáles son las secciones. Lo que importa son las directivas, porque analizas directivas.

Tenés que iterar por cada vez que encontrás una directiva {!--lang:xx--} acordándote de la anterior (si hay), siempre que esa directiva no esté dentro de un cacho de código.

(con { y } me refiero a <, [, ] y > según corresponda)

**Comment by diegoefe** [comment]
Creo que sí tengo que trackear secciones. Cómo hago sino para saber si me faltan lenguajes?

**Comment by emilioplatzer** [comment]
Si tenés la lista de lenguajes, tenés el orden en que deben aparecer. Después con las reglas 1.i, 2.iii y 3.i está la explicación. Si llamás `lenguajeAnterior` al que viste antes y `lenguajeActual` al que estás analizando y `lenguajeAnterior=='en'` y `lenguajeActual='fr'` y el orden era `en:xxx es:xxx fr:xxx`, por la regla 2.iii falta el lenguaje `'en'`. Y lo pude deducir de mirar el lenguaje actual, el anterior y el orden en que deben estar.

**Comment by diegoefe** [comment]
Eso es correcto, pero en qué momento realizo el chequeo si no detecto el fin de la sección? (en qué momento informo)

**Comment by emilioplatzer** [comment]
El momento es en cada iteración al detectar cada directiva {!--lang:xx--}, ahí si falla un control ya se determina que debe emitirse un warning.

**Comment by diegoefe** [comment]
Si no llegué a un \* o a lastLang (o si no encontré el mainlang) , cómo sé si me faltan otros?

Elemplo:
  langs: oo, xx, yy, zz 

Parseando....
1. lang:oo
2. lang:xx  -- acá como sé si me faltan yy o zz?
3. lang:yy
4. lang:*

Entonces: informo en 2. que me faltan yy y zz, en 3. que me falta zz, etc?
Se entiende?

**Comment by emilioplatzer** [comment]
No. 
1. en el renglón 1 ves lang oo, como es el primero no falta nada (si hubiera sido xx tampoco porque se acepta el segundo, y si fuera yy faltan (oo y xx) y si fuera zz la primera directiva que aparece entonces faltan oo, xx e yy
2. en el renglón 2 ves xx como el anterior visto (en el renglón 1) es oo y en la lista el anterior a xx es oo (o sea que hay coincidencia no falta nada)
3. en el renglón 3 pasa lo mismo yy tiene como anterior xx (tanto en la lista como lo que estás viendo) todo bien
4. en el renglón 4 ves un "_" entonces el anterior sí o sí debe ser el último de la lista (zz) pero el anterior al "_" es yy **no coinciden** salta un warning.

**Comment by diegoefe** [comment]
Creo que entendí

**Comment by diegoefe** [comment]
Elemplo:
son:  oo, xx, yy, zz
tengo: oo, *

Parseando....
    1. lang:oo
    2. lang:\* -> warning

2. debería generar tres warnings, uno para cada lang, todos con el mismo número de linea
Correcto?
O un warning con los tres langs?

**Comment by emilioplatzer** [comment]
sí, o uno la lista, lo que sea más fácil.

**Comment by diegoefe** [comment]
Cierro este que estamos con los detalles de esto en #15 y #11
