### ISSUE TITLE
Agregar Warning que controle que la última directiva lang termine en ">"

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#14]
Subimos caso de prueba skipeado

**Comment by diegoefe** [comment]
En el caso de prueba modifiqué la línea del warning final porque ese chequeo (last lang directive could\'n finish in "]") se hace al terminar el input

**Comment by emilioplatzer** [comment]
El chequeo que lo haga dónde sea. Pero que informe la línea donde está el
último lang

**Comment by diegoefe** [comment]
Lo mismo para esto 'last lang must be \"*\" or \"%"\"'?

**Comment by emilioplatzer** [comment]
diría que sí

**Comment by diegoefe** [comment]
Ya lo hice (era fácil de revertir si no lo querías)
