### ISSUE TITLE
No detecta el mismo idioma dos veces seguido

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#15]
Para reproducir el bug hay que clonar pg-promise-strict y ejecutar:

``` sh
c:\hecho\npm\pg-promise-strict>multilang docs\additions.md
Processing 'docs\additions.md'...
Generating all languages...
line 13: button section must be in main language or in all languages
Generating 'es', writing to 'c:\hecho\npm\pg-promise-strict\docs\agregados.md'...
Generated 'es', file 'c:\hecho\npm\pg-promise-strict\docs\agregados.md'.
Done!
c:\hecho\npm\pg-promise-strict>
```
- Falta un warning diciendo que falta una sección en inglés
- Sobra el warning que dice que la sección buttons debe estar en all languages porque ahí está.

**Comment by diegoefe** [comment]
Tal vez no estoy interpretando bien pero en 'docs\additions.md' veo que está dos veces lang:es (y eso es un warning) pero no falta el inglés.
Cómo lo ves vos?

**Comment by diegoefe** [comment]
Ahí subí la corrección con un caso de prueba. Cerrarlo cuando cotejes que esté bien
