### ISSUE TITLE
Cuando se lo corre con el parámetro -v (--verify) siempre genera files

### ISSUE THREAD

**Issue by diegoefe** [codenautas/multilang#16]
No existe referencia al parámetro ni multilang.js, ni en multilang-run.js

**Comment by diegoefe** [comment]
Para resolverlo, además de evitar los writeFile(), habría que:
1. Generar una salida (forzarla aunque exista --silent) formateada para su fácil parseo, o
2. Escribir un .log con los errores, si tales

Qué opinás?

**Comment by diegoefe** [comment]
Lo cierro porque está mal formulado, el parámetro es --check (-c), no --verify (-v) y la ejecución del mismo no escribe archivos

**Comment by emilioplatzer** [comment]
Controlar que entonces -v exista y signifique algo útil (y por lo tanto sea correcto que genere archivos) o si -v es --version igual no debe generar o si la opción no existe debe avisar y no seguir (y no generar)

**Comment by diegoefe** [comment]
- -v es --verbose
- -s es --silent
- -c es --check (correr multilang sin generar achivos)
- Si se utiliza -c con cualquier otra combinación, no genera archivos

**Comment by emilioplatzer** [comment]
Perfecto
