### ISSUE TITLE
Agregar la opción --verbose para info no necesaria y arreglar --silent

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#17]
Si no se especifica --verbose solo deben aparecer los warnings

Si se especifica --silent y todo anda bien no debe aparecer nada (ni Done!), solo deben aparecer los runtime errors si hubieran. 

Actualmente al poner multilang aparece algo así como

``` sh
c:\Hecho\npm\js-to-html>multilang README.md
Processing 'README.md'...
Generating all languages...
line 113: unbalanced start "["
line 113: unbalanced "<"
Generating 'es', writing to 'c:\Hecho\npm\js-to-html\LEEME.md'...
Generated 'es', file 'c:\Hecho\npm\js-to-html\LEEME.md'.
Done!
```

Esa tendría que ser la salida de --verbose. Sin --verbose tiene que sacar solo los warnings

``` sh
c:\Hecho\npm\js-to-html>multilang README.md
line 113: unbalanced start "["
line 113: unbalanced "<"
```

Actualmente con --silent aparece Done!, no debería. Si hay runtime errors sí deberían aparecer.

**Comment by diegoefe** [comment]
Al tratar de agregar --verbose me dí cuenta de que existe --verify que usa -v.
Agregué --verbose sólo. Si no hay mucha dependencias y te parece puedo mover -v/--verify a -c/--check-only y hacer que -v sea para --verbose

**Comment by diegoefe** [comment]
Del último comentario del párrafo inicial (Actualmente con --silent aparece Done!, no debería. **Si hay runtime errors sí deberían aparecer**) se desprende que los warnings (entiendo que esos son los runtime errors)  siempre deberían aparecer, entonces:
1. Es esta interpretación correcta?
2. En los tests del main aparecen los warnings en pantalla si 1. es verdad

**Comment by emilioplatzer** [comment]
Los warnings no son lo runtime errors. 
- Los warnings son mensajes que el programa tiene contemplado mostrar cuando los controles que hace no cumplen los criterios establecidos
- Los runtime error son los errores no contemplados dentro del programa (por ejemplo se quita el pendrive en el momento en que se está leyendo el archivo). Esos tienen que mostrarse igual que siempre aunque se le pase el parámetro --silent o cualquier otro.

**Comment by diegoefe** [comment]
Ah, los runtime errors son las excepciones y siempre se muestran.
Y los warnings, aunque haya, no se muestran si se pasa --silent
Correcto?

**Comment by emilioplatzer** [comment]
Correcto
