### ISSUE TITLE
Agregar la opcion --strip-comment --no-strip-comment

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#21]
Con `--strip-comment` (o cuando el nombre del archivo es `README.md`) quitar todos los comentarios de dentro del generado. (salvo que esté en un bloque de código que empiece con tres apóstrofes invertidos). 

Si el archivo es `README.md` y se especifica `--no-strip-comment` no se hace el strip

El strip debería quitar el renglón entero, o sea si el comentario termina en un fin de línea (`\r\n` o en un `\n`) hay que quitar también el fin de línea .

**Comment by emilioplatzer** [comment]
En realidad solo hay que quitar el fin de línea si el comienzo del comentario está al comienzo de la línea (en la columna 1)

**Comment by emilioplatzer** [comment]
Quedó un detallecito. Subo el caso corregido

**Comment by diegoefe** [comment]
No utilizar 1.0.8!, aún tiene un bug (agrego casos de prueba y corrijo en breve)
