### ISSUE TITLE
Avisar si se especifica una versión de qa-control que no existe

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#23]
Esa es la primera regla y es válida para todas las reglas. Si esta falla se deja de controlar el resto. 

Tiene que haber un conjunto de reglas que no dependa de la versión. 

En LoadProject hay que agregar el campo info.version que será el que después se use para acceder al conjunto de reglas específico (si es que la versión es válida y existe)

**Comment by diegoefe** [comment]
Cerrada por agregada a este proyecto de manera equivocada
