### ISSUE TITLE
investigar cómo hacer la versión *command line*

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#4]
Mirar el paquete npm-check-updates

Ver cómo se instala globalmente y cómo genera los archivos .cmd y dónde los pone

**Comment by emilioplatzer** [comment]
Averiguar la manera más estándar de definir parámetros. 

comando [opts] poscionales...

**Comment by diegoefe** [comment]
Por ahora commander es el mejor que encontré.
