### ISSUE TITLE
Implementar la función principal

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#5]
La función principal es la que se llamará desde la línea de comandos
# multilang.main = function main(parameters)
## uso típico:

``` sh
multilang README.md
```
## otro uso posible

(en el #4 decidiremos dónde van las opciones)

``` sh
multilang README.md --lang es --out README.es --verify
```

| parameters | tipo | default | uso |
| --- | --- | --- | --- |
| input | posicional | obligatorio | Nombre del archivo de entrada que contiene el MD multiline |
| lang | optativo | todos los lenguajes definidos | lenguaje que va a exportarse |
| out | optativo | lo deduce del input | el nombre del archivo de salida, no puede especificarse si no se especificó lang |
| verify | optativo | false | No graba la respuesta, lo que hace es leer y comparar que sea igual |
| silent | optativo | false | No muestra información de progreso por chanout |
| chanout | interna | stdout | Stream por donde mostrar la salida (salvo que sea silent) |
| chanerr | interna | stderr | Stream por donde mostrar los errores de verify |
## ejemplo

Dentro de un test a la función se la podría llamar así:

``` js
var dummyErrStream=new StreamStringWriter(); // si es que existe
multilang.main({
    input: 'README.md',
    lang: 'es',
    out: 'LEEME-errado.md',
    verify: true,
    chanerr: dummyErrStream
});

expect(dummyErrStream).to.eql(
  "Error in line 14..."
);
```

La función devuelve un número que si es distinto de 0 debe llamarse a process.exit(n)

**Comment by diegoefe** [comment]
chanout/err dice que son de uso interno, cómo te lo imaginás?

**Comment by emilioplatzer** [comment]
Mi idea es que las de uso interno no puedan modificarse desde la línea de comandos. 

Son para las pruebas o para invocarlo desde un servicio web (o sea sí las puede recibir multilang.main).

**Comment by diegoefe** [comment]
Ah. Ok

**Comment by diegoefe** [comment]
Pregunta: el caso de prueba 'do simple task' envía 'xx' y 'OUTPUT.md' respectivamente, la salida no debería ser 'OUTPUT.md-xx.md' (o enviar 'OUTPUT' en parameters.out y esperar OUTPUT-xx.md)?
Cómo es?

**Comment by diegoefe** [comment]
Con respecto a lang/out y su optatividad: Si no son especificados, deben
generarse todos los lenguajes en la carpeta actual, correcto?
El problema es que changeDoc() no nos dice qué está generando.

Entonces para este caso se me ocurren dos alternativas:
- Cambiar changeDoc() para que diga qué archivo va a generar para
  poder escribir la salida desde main(). Por ejemplo devolviendo un
  objeto con el path y el contenido.

o
- Separar la interpretación de lo que hay que generar, de la generación
  (actualmente todo en changeDoc()) para poder controlarlo desde main()
  (esta opción va a hacer explotar los expectCalled() de los tests).
  De esta forma changeDoc() se usa para generar de a uno y los otros
  sub-métodos se llaman desde main() una vez para cada documento a generar

Tiene sentido? Qué preferís? (o si se te ocurre otra cosa mejor)

**Comment by emilioplatzer** [comment]
Mi idea era que out solo se pudiera especificar si se ponía lang. Si querés
agregá otro parámetro --outPrefixName ó --out-prefix-name (como se escriba)
que se pueda especificar con o sin lang

2015-04-21 15:30 GMT-03:00 Diego Florio notifications@github.com:

**Comment by emilioplatzer** [comment]
sin lang antes hay que llamar a obtainLangs y llamar a changeDoc por cada
uno de los lenguajes obtenidos. obtainLangs ya te dice el nombre de archivo
de salida.

2015-04-21 15:51 GMT-03:00 Diego Florio notifications@github.com:

**Comment by diegoefe** [comment]
Sí, pero changeDoc() también llama a obtainLangs() lo cual es redundante (2
veces por cada lenguaje) por eso es que propuse lo anterior

2015-04-21 17:08 GMT-03:00 Emilio notifications@github.com:

**Comment by emilioplatzer** [comment]
No es grave.

2015-04-21 17:11 GMT-03:00 Diego Florio notifications@github.com:

**Comment by diegoefe** [comment]
ok

2015-04-21 17:13 GMT-03:00 Emilio notifications@github.com:

**Comment by diegoefe** [comment]
Cómo ves una opción --propt-if-exists (default:false) o --ovewrite-existing (default: true)?
Para más adelante

**Comment by diegoefe** [comment]
Sin duda tiene que haber un chequeo de que input y output sean diferentes

**Comment by emilioplatzer** [comment]
Bien.

**Comment by diegoefe** [comment]
Quedaría: --propt-if-exists (default:false) o --ovewrite-existing (default: true)
Cerramos este y agregamos otro ticket?

**Comment by emilioplatzer** [comment]
sí, cerramos este y eso lo ponemos en otro con baja prioridad
