### ISSUE TITLE
Implementar la llamada a multilang.main

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#6]

**Comment by diegoefe** [comment]
Está subida la primera implementación tentativa en bin/multilang_run.js, super-provisoria

**Comment by diegoefe** [comment]
Queda resolver:
- Chequeo de input <> output
- Que se pueda correr desde un directorio que no sea la raíz de multilang (a investigar)
- Verificar que esté bien la recursión asíncrona al generar todos los lenguages
- Tests

**Comment by emilioplatzer** [comment]
No debe generar el archivo del main language

**Comment by diegoefe** [comment]
Listo
