### ISSUE TITLE
Agregar el parámetro output-path

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#7]
Los output los genera en la carpeta especificada en output-path

Si no está especificado debe tomar la carpeta del parámetro input

Si alguien quiere la carpeta actual pondrá `--output-path .`

**Comment by diegoefe** [comment]
Lo definí como:
.option('-d, --directory [name]', 'Name of the output directory.')
porque -o ya está usado en --output
Te parece bien?

**Comment by emilioplatzer** [comment]
sí

**Comment by diegoefe** [comment]
Listo
