### ISSUE TITLE
Falla al usar el multilang-run sin --lang para js-to-html

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#8]
Para reproducirlo:
1. Hacer git-clone de multilang y de js-to-html colgando de la misma carpeta (en mi caso fue _c:\hecho\npm_)
2. Ejecutar lo que acá se indica:

``` sh
c:\hecho\npm\multilang>node bin/multilang-run.js c:\hecho\npm\js-to-html\README.md
Using directory:  c:\hecho\npm\js-to-html
Processing 'c:\hecho\npm\js-to-html\README.md'...
Generating all languages...

c:\hecho\npm\multilang>
```
1. Ver que no se generó nada.

**Comment by emilioplatzer** [comment]
Ahí anduvo (el problema es que multilang.js no compilaba porque faltaba la definición de una variable). 

Esto no debería pasar. Si multilang.js no compila multilang-run debería mandar un mensaje de error

**Comment by diegoefe** [comment]
De acuerdo.
Es muy raro porque yo nunca subo algo sin correr los tests.

2015-04-29 11:05 GMT-03:00 Emilio notifications@github.com:

**Comment by diegoefe** [comment]
Podés chatear?

2015-04-29 11:07 GMT-03:00 Diego F. diegoefe@gmail.com:

**Comment by diegoefe** [comment]
Este no estará resuelto ya?

**Comment by emilioplatzer** [comment]
Es probable. Tenía una aclaración. Me fijo

**Comment by emilioplatzer** [comment]
Sigue fallando. Para reproducirlo agregá una línea en la función main para que quede así:

``` js
multilang.main=function main(parameters){
    return Promise.reject(3);
...
```

Debería informar que hubo un error en main

**Comment by emilioplatzer** [comment]
Sigue fallando. Para reproducirlo agregá una línea en la función main para que quede así:

```js
multilang.main=function main(parameters){
    return Promise.reject(3);
...
```

Debería informar que hubo un error en main

**Comment by diegoefe** [comment]
Lo miro

**Comment by diegoefe** [comment]
Lo corrí con:
  D:\cn\mlang>node bin/multilang**-run.js** d:\cn\js-to-html\README.md
Y esta es la salida:
Using directory:  d:\cn\js-to-html
Processing 'd:\cn\js-to-html\README.md'...
Generating all languages...
Generating 'es', writing to 'd:\cn\js-to-html\LEEME.md'...
Generated 'es', file 'd:\cn\js-to-html\LEEME.md'.
Done!
Y generó bien

**Comment by emilioplatzer** [comment]
Imposible que genere eso si ponés return Promise.reject() en la primera
línea del main

**Comment by diegoefe** [comment]
Ya sé, no había hecho eso (ahora sí) y es lógico que falle.
Estaba comentada la línea que mostraba el posible error (ahora la corrijo y lo subo).
Pero entendí que el problema más importante era que no generaba los archivos.
Y eso me anduvo
