### ISSUE TITLE
Que respete los espacios de los encabezados

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/multilang#9]
Quizás haya que cambiar algún caso de prueba (en especial los generados por multilanguage).

**Comment by diegoefe** [comment]
Fijate si puede cerrarse este

**Comment by emilioplatzer** [comment]
El código en case 'buttons':  de changeDoc está raro, no entiendo qué hace
¿cómo llegué ahí? sacando el último skip que queda.

Cuando dice buttons hay que poner el generated buttons y punto.

Quizás esté mal otra cosa más arriba o en otro caso de prueba o en otra
función. Algo raro hay y no me doy cuenta qué.

Empezá por sacar el skip y eso te va a ordenar el resto

**Comment by diegoefe** [comment]
Se me pasó el skip, por eso no corregí esa parte.
Tuve que cambiar generateButtons() porque el encabezado/comentario ('\n') no es un solo bloque con los botones, porque vos querés que te deje poner un espacio o cualquier cosa en el medio y al final (hasta que hay dos líneas vacías):

```
<!--multilang buttons-->
texto
teexto
idioma: ![castellano](https://raw.githubusercontent.com/codenautas/multilang/master/img/lang-es.png)
también disponible en:
[![inglés](https://raw.githubusercontent.com/codenautas/multilang/master/img/lang-en.png)](with-spaces.md)
más texto

siguiente bloque
```

entonces tuve que cambiar el algoritmo porque generate buttons recibía un objeto devuelto por obtainedLangs(), mirá el commit anterior.
Por eso hay casos en los que obtainedLangs() sólo genera el contenidos (los botones).
Se te ocurre una manera mejor?
O corrijo 'generate the french text of the fake' para que pase?

**Comment by emilioplatzer** [comment]
El generate text french está bien, que que genere GenerateButtons es lo que
hay que poner.

GenerateButtons tiene que agregar una línea en blanco entre la directiva e
idioma

2015-05-05 13:46 GMT-03:00 Diego Florio notifications@github.com:

**Comment by diegoefe** [comment]
Tal vez no entendí bien, lo que describo antes (https://github.com/codenautas/multilang/issues/9#issuecomment-99137013), es correcto?
A la modificación ésta la tuve que hacer de acuerdo a eso que entendí.
(es lógico que 'generate the french text of the fake' falle así como está, luego de las modificaciones, repito que me olvidé de sacarle el skip)
Cómo es?
